SELECT
    R.SESSION_ID,
    R.COMMAND AS DS_OPERACAO,
    B.NAME AS NM_BANCO,
    R.START_TIME AS DT_INICIO,
    CONVERT(VARCHAR(20), DATEADD(MS, R.ESTIMATED_COMPLETION_TIME, GETDATE()), 20) AS DT_PREVISAO_FIM,
    CONVERT(NUMERIC(6, 2), R.PERCENT_COMPLETE) AS VL_PERCENTUAL_CONCLUIDO,
    CONVERT(NUMERIC(6, 2), R.TOTAL_ELAPSED_TIME / 1000.0 / 60.0) AS QT_MINUTOS_EXECUCAO,
    CONVERT(NUMERIC(6, 2), R.ESTIMATED_COMPLETION_TIME / 1000.0 / 60.0) AS QT_MINUTOS_RESTANTES,
    CONVERT(NUMERIC(6, 2), R.ESTIMATED_COMPLETION_TIME / 1000.0 / 60.0 / 60.0) AS QT_HORAS_RESTANTES,
    CONVERT(VARCHAR(MAX), ( SELECT
                                SUBSTRING(TEXT, R.STATEMENT_START_OFFSET / 2, CASE WHEN R.STATEMENT_END_OFFSET = -1 THEN 1000 ELSE ( R.STATEMENT_END_OFFSET - R.STATEMENT_START_OFFSET ) / 2 END)
                            FROM
                                SYS.DM_EXEC_SQL_TEXT(SQL_HANDLE)
                            )) AS DS_COMANDO
FROM
    SYS.DM_EXEC_REQUESTS    R    WITH(NOLOCK)
    JOIN SYS.DATABASES        B    WITH(NOLOCK)     ON R.DATABASE_ID = B.DATABASE_ID
WHERE
    R.COMMAND IN ( 
        'BACKUP DATABASE', 
        'RESTORE DATABASE', 
        'ALTER INDEX REORGANIZE', 
        'AUTO_SHRINK OPTION WITH ALTER DATABASE', 
        'CREATE INDEX',
        'DBCC CHECKDB',
        'DBCC CHECKFILEGROUP',
        'DBCC CHECKTABLE',
        'DBCC INDEXDEFRAG',
        'DBCC SHRINKDATABASE',
        'DBCC SHRINKFILE',
        'KILL',
        'UPDATE STATISTICS',
        'DBCC'
    )
    AND R.ESTIMATED_COMPLETION_TIME > 0 