SELECT
    A.[NAME] AS [DATABASE_NAME],
    A.RECOVERY_MODEL_DESC,
    (SELECT SUM(CAST(SIZE / 128 / 1024.0 AS NUMERIC(18, 2))) FROM SYS.MASTER_FILES WHERE A.[NAME] = [NAME]) AS SIZE_GB,
    MAX(B.BACKUP_START_DATE) AS LAST_BACKUP_DATE
FROM
    SYS.DATABASES A
    LEFT JOIN MSDB.DBO.BACKUPSET B ON A.[NAME] = B.[DATABASE_NAME]
WHERE
    (B.BACKUP_SET_ID IS NULL OR DATEDIFF(DAY, B.BACKUP_START_DATE, GETDATE()) > 7)
    AND A.[NAME] NOT IN ('TEMPDB', 'MODEL')
GROUP BY
    A.[NAME],
    A.RECOVERY_MODEL_DESC