SELECT
    DB_NAME(FS.DATABASE_ID) AS [DATABASE NAME],
    MF.PHYSICAL_NAME,
    IO_STALL_READ_MS,
    NUM_OF_READS,
    CAST(IO_STALL_READ_MS / ( 1.0 + NUM_OF_READS ) AS NUMERIC(10, 1)) AS [AVG_READ_STALL_MS],
    IO_STALL_WRITE_MS,
    NUM_OF_WRITES,
    CAST(IO_STALL_WRITE_MS / ( 1.0 + NUM_OF_WRITES ) AS NUMERIC(10, 1)) AS [AVG_WRITE_STALL_MS],
    IO_STALL_READ_MS + IO_STALL_WRITE_MS AS [IO_STALLS],
    NUM_OF_READS + NUM_OF_WRITES AS [TOTAL_IO],
    CAST(( IO_STALL_READ_MS + IO_STALL_WRITE_MS ) / ( 1.0 + NUM_OF_READS + NUM_OF_WRITES ) AS NUMERIC(10, 1)) AS [AVG_IO_STALL_MS]
FROM
    SYS.DM_IO_VIRTUAL_FILE_STATS(NULL, NULL) AS FS
    INNER JOIN SYS.MASTER_FILES AS MF WITH ( NOLOCK ) ON FS.DATABASE_ID = MF.DATABASE_ID AND FS.[FILE_ID] = MF.[FILE_ID]
ORDER BY
    AVG_IO_STALL_MS DESC;