SELECT
    B.[DATABASE_NAME],
    (CASE B.[TYPE]
        WHEN 'D' THEN 'FULL BACKUP'
        WHEN 'I' THEN 'DIFFERENTIAL BACKUP'
        WHEN 'L' THEN 'TLOG BACKUP'
        WHEN 'F' THEN 'FILE OR FILEGROUP'
        WHEN 'G' THEN 'DIFFERENTIAL FILE'
        WHEN 'P' THEN 'PARTIAL'
        WHEN 'Q' THEN 'DIFFERENTIAL PARTIAL'
    END) AS BACKUPTYPE,
    B.RECOVERY_MODEL AS RECOVERYMODEL,
    B.BACKUP_START_DATE,
    B.BACKUP_FINISH_DATE,
    CAST(DATEDIFF(SECOND,B.BACKUP_START_DATE, B.BACKUP_FINISH_DATE) AS VARCHAR(4)) + ' ' + 'SECONDS' AS TOTALTIMETAKEN,
    B.EXPIRATION_DATE,
    B.[USER_NAME],
    B.MACHINE_NAME,
    B.IS_PASSWORD_PROTECTED,
    B.COLLATION_NAME,
    B.IS_COPY_ONLY,
    CONVERT(NUMERIC(20, 2), B.BACKUP_SIZE / 1048576) AS BACKUPSIZEMB,
    A.LOGICAL_DEVICE_NAME,
    A.PHYSICAL_DEVICE_NAME,
    B.[NAME] AS BACKUPSET_NAME,
    B.[DESCRIPTION],
    B.HAS_BACKUP_CHECKSUMS,
    B.IS_DAMAGED,
    B.HAS_INCOMPLETE_METADATA
FROM
    SYS.DATABASES X
    JOIN MSDB.DBO.BACKUPSET B ON X.[NAME] = B.[DATABASE_NAME]
    JOIN MSDB.DBO.BACKUPMEDIAFAMILY A ON A.MEDIA_SET_ID = B.MEDIA_SET_ID
WHERE
    B.BACKUP_START_DATE >= CONVERT(DATE, DATEADD(DAY, -7, GETDATE()))
