SELECT
    A.[RESTORE_HISTORY_ID],
    A.[RESTORE_DATE],
    A.[DESTINATION_DATABASE_NAME],
    C.PHYSICAL_DEVICE_NAME,
    A.[USER_NAME],
    A.[BACKUP_SET_ID],
    CASE A.[RESTORE_TYPE]
        WHEN 'D' THEN 'DATABASE'
        WHEN 'I' THEN 'DIFFERENTIAL'
        WHEN 'L' THEN 'LOG'
        WHEN 'F' THEN 'FILE'
        WHEN 'G' THEN 'FILEGROUP'
        WHEN 'V' THEN 'VERIFYONLYL'
    END AS RESTORETYPE,
    A.[REPLACE],
    A.[RECOVERY],
    A.[RESTART],
    A.[STOP_AT],
    A.[DEVICE_COUNT],
    A.[STOP_AT_MARK_NAME],
    A.[STOP_BEFORE]
FROM
    [MSDB].[DBO].[RESTOREHISTORY] A
    JOIN [MSDB].[DBO].[BACKUPSET] B ON A.BACKUP_SET_ID = B.BACKUP_SET_ID
    JOIN MSDB.DBO.BACKUPMEDIAFAMILY C ON B.MEDIA_SET_ID = C.MEDIA_SET_ID
WHERE
    A.RESTORE_DATE >= CONVERT(DATE, DATEADD(DAY, -7, GETDATE()))
