SELECT 
    S.[NAME] AS [SCHEMA],
    T.[NAME] AS [TABLE_NAME],
    I.[NAME] AS [INDEX_NAME],
    I.[TYPE_DESC],
    P.[ROWS] AS [ROW_COUNT],
    CAST(ROUND(((SUM(A.TOTAL_PAGES) * 8) / 1024.00), 2) AS NUMERIC(36, 2)) AS [SIZE_MB],
    CAST(ROUND(((SUM(A.USED_PAGES) * 8) / 1024.00), 2) AS NUMERIC(36, 2)) AS [USED_MB], 
    CAST(ROUND(((SUM(A.TOTAL_PAGES) - SUM(A.USED_PAGES)) * 8) / 1024.00, 2) AS NUMERIC(36, 2)) AS [UNUSED_MB]
FROM
    SYS.TABLES T
    JOIN SYS.INDEXES I ON T.[OBJECT_ID] = I.[OBJECT_ID]
    JOIN SYS.PARTITIONS P ON I.[OBJECT_ID] = P.[OBJECT_ID] AND I.INDEX_ID = P.INDEX_ID
    JOIN SYS.ALLOCATION_UNITS A ON P.[PARTITION_ID] = A.CONTAINER_ID
    LEFT JOIN SYS.SCHEMAS S ON T.[SCHEMA_ID] = S.[SCHEMA_ID]
WHERE 
    T.IS_MS_SHIPPED = 0
    AND I.[OBJECT_ID] > 255 
GROUP BY
    T.[NAME], 
    S.[NAME],
    I.[NAME],
    I.[TYPE_DESC],
    P.[ROWS]
ORDER BY 
    [SIZE_MB] DESC