SELECT
    DB_NAME(MF.DATABASE_ID) AS [DATABASE],
    MF.PHYSICAL_NAME,
    R.IO_PENDING,
    R.IO_PENDING_MS_TICKS,
    R.IO_TYPE,
    FS.NUM_OF_READS,
    FS.NUM_OF_WRITES,
    GETDATE()
FROM
    SYS.DM_IO_PENDING_IO_REQUESTS AS R
    INNER JOIN SYS.DM_IO_VIRTUAL_FILE_STATS(NULL, NULL) AS FS ON R.IO_HANDLE = FS.FILE_HANDLE
    INNER JOIN SYS.MASTER_FILES AS MF ON FS.DATABASE_ID = MF.DATABASE_ID AND FS.FILE_ID = MF.FILE_ID
ORDER BY
    R.IO_PENDING,
    R.IO_PENDING_MS_TICKS DESC