SELECT TOP(100)
    DB_NAME(C.[DBID]) AS [DATABASE],
    B.[TEXT],
    (SELECT CAST(SUBSTRING(B.[TEXT], (A.STATEMENT_START_OFFSET/2)+1,   
        (((CASE A.STATEMENT_END_OFFSET  
            WHEN -1 THEN DATALENGTH(B.[TEXT]) 
            ELSE A.STATEMENT_END_OFFSET  
        END) - A.STATEMENT_START_OFFSET)/2) + 1) AS NVARCHAR(MAX)) FOR XML PATH(''), TYPE) AS [TSQL],
    C.QUERY_PLAN,
 
    A.LAST_EXECUTION_TIME,
    A.EXECUTION_COUNT,
 
    A.TOTAL_ELAPSED_TIME / 1000 AS TOTAL_ELAPSED_TIME_MS,
    A.LAST_ELAPSED_TIME / 1000 AS LAST_ELAPSED_TIME_MS,
    A.MIN_ELAPSED_TIME / 1000 AS MIN_ELAPSED_TIME_MS,
    A.MAX_ELAPSED_TIME / 1000 AS MAX_ELAPSED_TIME_MS,
    ((A.TOTAL_ELAPSED_TIME / A.EXECUTION_COUNT) / 1000) AS AVG_ELAPSED_TIME_MS,
 
    A.TOTAL_WORKER_TIME / 1000 AS TOTAL_WORKER_TIME_MS,
    A.LAST_WORKER_TIME / 1000 AS LAST_WORKER_TIME_MS,
    A.MIN_WORKER_TIME / 1000 AS MIN_WORKER_TIME_MS,
    A.MAX_WORKER_TIME / 1000 AS MAX_WORKER_TIME_MS,
    ((A.TOTAL_WORKER_TIME / A.EXECUTION_COUNT) / 1000) AS AVG_WORKER_TIME_MS,
   
    A.TOTAL_PHYSICAL_READS,
    A.LAST_PHYSICAL_READS,
    A.MIN_PHYSICAL_READS,
    A.MAX_PHYSICAL_READS,
   
    A.TOTAL_LOGICAL_READS,
    A.LAST_LOGICAL_READS,
    A.MIN_LOGICAL_READS,
    A.MAX_LOGICAL_READS,
   
    A.TOTAL_LOGICAL_WRITES,
    A.LAST_LOGICAL_WRITES,
    A.MIN_LOGICAL_WRITES,
    A.MAX_LOGICAL_WRITES
FROM
    SYS.DM_EXEC_QUERY_STATS A
    CROSS APPLY SYS.DM_EXEC_SQL_TEXT(A.[SQL_HANDLE]) B
    OUTER APPLY SYS.DM_EXEC_QUERY_PLAN (A.PLAN_HANDLE) AS C
ORDER BY
    A.TOTAL_ELAPSED_TIME DESC
