SELECT
    A.REQUEST_SESSION_ID AS SESSION_ID,
    COALESCE(G.START_TIME, F.LAST_REQUEST_START_TIME) AS START_TIME,
    COALESCE(G.OPEN_TRANSACTION_COUNT, F.OPEN_TRANSACTION_COUNT) AS OPEN_TRANSACTION_COUNT,
    A.RESOURCE_DATABASE_ID,
    DB_NAME(A.RESOURCE_DATABASE_ID) AS DBNAME,
    (CASE WHEN A.RESOURCE_TYPE = 'OBJECT' THEN D.[NAME] ELSE E.[NAME] END) AS OBJECTNAME,
    (CASE WHEN A.RESOURCE_TYPE = 'OBJECT' THEN D.IS_MS_SHIPPED ELSE E.IS_MS_SHIPPED END) AS IS_MS_SHIPPED,
    B.INDEX_ID,
    C.[NAME] AS INDEX_NAME,
    A.RESOURCE_TYPE,
    A.RESOURCE_DESCRIPTION,
    A.RESOURCE_ASSOCIATED_ENTITY_ID,
    A.REQUEST_MODE,
    A.REQUEST_STATUS,
    F.LOGIN_NAME,
    F.[PROGRAM_NAME],
    F.[HOST_NAME],
    G.BLOCKING_SESSION_ID
FROM
    SYS.DM_TRAN_LOCKS A WITH(NOLOCK)
    LEFT JOIN SYS.PARTITIONS B WITH(NOLOCK) ON B.HOBT_ID = A.RESOURCE_ASSOCIATED_ENTITY_ID
    LEFT JOIN SYS.INDEXES C WITH(NOLOCK) ON C.[OBJECT_ID] = B.[OBJECT_ID] AND C.INDEX_ID = B.INDEX_ID
    LEFT JOIN SYS.OBJECTS D WITH(NOLOCK) ON A.RESOURCE_ASSOCIATED_ENTITY_ID = D.[OBJECT_ID]
    LEFT JOIN SYS.OBJECTS E WITH(NOLOCK) ON B.[OBJECT_ID] = E.[OBJECT_ID]
    LEFT JOIN SYS.DM_EXEC_SESSIONS F WITH(NOLOCK) ON A.REQUEST_SESSION_ID = F.SESSION_ID
    LEFT JOIN SYS.DM_EXEC_REQUESTS G WITH(NOLOCK) ON A.REQUEST_SESSION_ID = G.SESSION_ID
WHERE
    A.RESOURCE_ASSOCIATED_ENTITY_ID > 0
    AND A.RESOURCE_DATABASE_ID = DB_ID()
    AND A.RESOURCE_TYPE = 'OBJECT'
    AND (CASE WHEN A.RESOURCE_TYPE = 'OBJECT' THEN D.IS_MS_SHIPPED ELSE E.IS_MS_SHIPPED END) = 0
ORDER BY
    A.REQUEST_SESSION_ID,
    A.RESOURCE_ASSOCIATED_ENTITY_ID
