SELECT 
    B.[NAME] AS DS_USUARIO,
    C.[NAME] AS DS_SERVER_ROLE
FROM 
    SYS.SERVER_ROLE_MEMBERS A
    JOIN SYS.SERVER_PRINCIPALS B ON A.MEMBER_PRINCIPAL_ID = B.PRINCIPAL_ID
    JOIN SYS.SERVER_PRINCIPALS C ON A.ROLE_PRINCIPAL_ID = C.PRINCIPAL_ID
