SELECT
    C.[NAME] AS DS_USUARIO,
    B.[NAME] AS DS_DATABASE_ROLE
FROM 
    SYS.DATABASE_ROLE_MEMBERS A
    JOIN SYS.DATABASE_PRINCIPALS B ON A.ROLE_PRINCIPAL_ID = B.PRINCIPAL_ID
    JOIN SYS.DATABASE_PRINCIPALS C ON A.MEMBER_PRINCIPAL_ID = C.PRINCIPAL_ID