SELECT
    A.CLASS_DESC AS DS_TIPO_PERMISSAO, 
    A.[PERMISSION_NAME] AS DS_PERMISSAO,
    A.STATE_DESC AS DS_OPERACAO,
    B.[NAME] AS DS_USUARIO_PERMISSAO,
    C.[NAME] AS DS_LOGIN_PERMISSAO,
    D.[NAME] AS DS_OBJETO
FROM 
    SYS.DATABASE_PERMISSIONS A
    JOIN SYS.DATABASE_PRINCIPALS B ON A.GRANTEE_PRINCIPAL_ID = B.PRINCIPAL_ID
    LEFT JOIN SYS.SERVER_PRINCIPALS C ON B.[SID] = C.[SID]
    LEFT JOIN SYS.OBJECTS D ON A.MAJOR_ID = D.[OBJECT_ID]
WHERE
    A.MAJOR_ID >= 0