SELECT
    B.START_TIME,
    A.SESSION_ID,
    B.COMMAND,
    A.LOGIN_NAME,
    A.[HOST_NAME],
    A.[PROGRAM_NAME],
    B.LOGICAL_READS,
    B.CPU_TIME,
    B.WRITES,
    B.BLOCKING_SESSION_ID,
    C.QUERY_PLAN
FROM
    SYS.DM_EXEC_SESSIONS AS A WITH (NOLOCK)
    LEFT JOIN SYS.DM_EXEC_REQUESTS AS B WITH (NOLOCK) ON A.SESSION_ID = B.SESSION_ID
    OUTER APPLY SYS.DM_EXEC_QUERY_PLAN(B.[PLAN_HANDLE]) AS C
WHERE
    A.SESSION_ID > 50
    AND A.SESSION_ID <> @@SPID
    AND (A.[STATUS] <> 'SLEEPING' OR (A.[STATUS] = 'SLEEPING' AND A.OPEN_TRANSACTION_COUNT > 0))
ORDER BY
    B.START_TIME

