SELECT DISTINCT 
    C.[NAME] AS [SCHEMA],
    A.[NAME] AS TABELA,
    NULL AS INDICE,
    'ALTER TABLE [' + C.[NAME] + '].[' + A.[NAME] + '] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = PAGE)' AS COMANDO
FROM 
    SYS.TABLES                   A
    INNER JOIN SYS.PARTITIONS    B   ON A.[OBJECT_ID] = B.[OBJECT_ID]
    INNER JOIN SYS.SCHEMAS       C   ON A.[SCHEMA_ID] = C.[SCHEMA_ID]
WHERE 
    B.DATA_COMPRESSION_DESC = 'NONE'
    AND B.INDEX_ID = 0 -- HEAP
    AND A.[TYPE] = 'U'
    
UNION
 
SELECT DISTINCT 
    C.[NAME] AS [SCHEMA],
    B.[NAME] AS TABELA,
    A.[NAME] AS INDICE,
    'ALTER INDEX [' + A.[NAME] + '] ON [' + C.[NAME] + '].[' + B.[NAME] + '] REBUILD PARTITION = ALL WITH ( STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, SORT_IN_TEMPDB = OFF, DATA_COMPRESSION = PAGE)'
FROM 
    SYS.INDEXES                  A
    INNER JOIN SYS.TABLES        B   ON A.[OBJECT_ID] = B.[OBJECT_ID]
    INNER JOIN SYS.SCHEMAS       C   ON B.[SCHEMA_ID] = C.[SCHEMA_ID]
    INNER JOIN SYS.PARTITIONS    D   ON A.[OBJECT_ID] = D.[OBJECT_ID] AND A.INDEX_ID = D.INDEX_ID
WHERE
    D.DATA_COMPRESSION_DESC =  'NONE'
    AND D.INDEX_ID <> 0
    AND A.[TYPE] IN (1, 2) -- CLUSTERED E NONCLUSTERED (ROWSTORE)
    AND B.[TYPE] = 'U'
ORDER BY
    TABELA,
    INDICE
