SELECT
    CP.OBJTYPE AS OBJECTTYPE,
    OBJECT_NAME(ST.OBJECTID, ST.DBID) AS OBJECTNAME,
    CP.USECOUNTS AS EXECUTIONCOUNT,
    ST.TEXT AS QUERYTEXT,
    QP.QUERY_PLAN AS QUERYPLAN
FROM
    SYS.DM_EXEC_CACHED_PLANS AS CP
    CROSS APPLY SYS.DM_EXEC_QUERY_PLAN(CP.PLAN_HANDLE) AS QP
    CROSS APPLY SYS.DM_EXEC_SQL_TEXT(CP.PLAN_HANDLE) AS ST
ORDER BY
    EXECUTIONCOUNT DESC
