;WITH [WAITS]
AS ( SELECT
         [WAIT_TYPE],
         [WAIT_TIME_MS] / 1000.0 AS [WAITS],
         ( [WAIT_TIME_MS] - [SIGNAL_WAIT_TIME_MS] ) / 1000.0 AS [RESOURCES],
         [SIGNAL_WAIT_TIME_MS] / 1000.0 AS [SIGNALS],
         [WAITING_TASKS_COUNT] AS [WAITCOUNT],
         100.0 * [WAIT_TIME_MS] / SUM([WAIT_TIME_MS]) OVER () AS [PERCENTAGE],
         ROW_NUMBER() OVER ( ORDER BY
                                 [WAIT_TIME_MS] DESC
                           ) AS [ROWNUM]
     FROM
         SYS.DM_OS_WAIT_STATS
     WHERE
         [WAIT_TYPE] NOT IN (
                                -- THESE WAIT TYPES ARE ALMOST 100% NEVER A PROBLEM AND SO THEY ARE
                                -- FILTERED OUT TO AVOID THEM SKEWING THE RESULTS. CLICK ON THE URL
                                -- FOR MORE INFORMATION.
                                N'BROKER_EVENTHANDLER', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/BROKER_EVENTHANDLER
                                N'BROKER_RECEIVE_WAITFOR', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/BROKER_RECEIVE_WAITFOR
                                N'BROKER_TASK_STOP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/BROKER_TASK_STOP
                                N'BROKER_TO_FLUSH', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/BROKER_TO_FLUSH
                                N'BROKER_TRANSMITTER', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/BROKER_TRANSMITTER
                                N'CHECKPOINT_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/CHECKPOINT_QUEUE
                                N'CHKPT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/CHKPT
                                N'CLR_AUTO_EVENT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/CLR_AUTO_EVENT
                                N'CLR_MANUAL_EVENT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/CLR_MANUAL_EVENT
                                N'CLR_SEMAPHORE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/CLR_SEMAPHORE
                                N'CXCONSUMER', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/CXCONSUMER
 
                                -- MAYBE COMMENT THESE FOUR OUT IF YOU HAVE MIRRORING ISSUES
                                N'DBMIRROR_DBM_EVENT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/DBMIRROR_DBM_EVENT
                                N'DBMIRROR_EVENTS_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/DBMIRROR_EVENTS_QUEUE
                                N'DBMIRROR_WORKER_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/DBMIRROR_WORKER_QUEUE
                                N'DBMIRRORING_CMD', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/DBMIRRORING_CMD
 
                                N'DIRTY_PAGE_POLL', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/DIRTY_PAGE_POLL
                                N'DISPATCHER_QUEUE_SEMAPHORE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/DISPATCHER_QUEUE_SEMAPHORE
                                N'EXECSYNC', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/EXECSYNC
                                N'FSAGENT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/FSAGENT
                                N'FT_IFTS_SCHEDULER_IDLE_WAIT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/FT_IFTS_SCHEDULER_IDLE_WAIT
                                N'FT_IFTSHC_MUTEX', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/FT_IFTSHC_MUTEX
 
                                -- MAYBE COMMENT THESE SIX OUT IF YOU HAVE AG ISSUES
                                N'HADR_CLUSAPI_CALL', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/HADR_CLUSAPI_CALL
                                N'HADR_FILESTREAM_IOMGR_IOCOMPLETION', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/HADR_FILESTREAM_IOMGR_IOCOMPLETION
                                N'HADR_LOGCAPTURE_WAIT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/HADR_LOGCAPTURE_WAIT
                                N'HADR_NOTIFICATION_DEQUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/HADR_NOTIFICATION_DEQUEUE
                                N'HADR_TIMER_TASK', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/HADR_TIMER_TASK
                                N'HADR_WORK_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/HADR_WORK_QUEUE
 
                                N'KSOURCE_WAKEUP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/KSOURCE_WAKEUP
                                N'LAZYWRITER_SLEEP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/LAZYWRITER_SLEEP
                                N'LOGMGR_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/LOGMGR_QUEUE
                                N'MEMORY_ALLOCATION_EXT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/MEMORY_ALLOCATION_EXT
                                N'ONDEMAND_TASK_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/ONDEMAND_TASK_QUEUE
                                N'PARALLEL_REDO_DRAIN_WORKER', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PARALLEL_REDO_DRAIN_WORKER
                                N'PARALLEL_REDO_LOG_CACHE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PARALLEL_REDO_LOG_CACHE
                                N'PARALLEL_REDO_TRAN_LIST', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PARALLEL_REDO_TRAN_LIST
                                N'PARALLEL_REDO_WORKER_SYNC', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PARALLEL_REDO_WORKER_SYNC
                                N'PARALLEL_REDO_WORKER_WAIT_WORK', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PARALLEL_REDO_WORKER_WAIT_WORK
                                N'PREEMPTIVE_XE_GETTARGETSTATE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PREEMPTIVE_XE_GETTARGETSTATE
                                N'PWAIT_ALL_COMPONENTS_INITIALIZED', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PWAIT_ALL_COMPONENTS_INITIALIZED
                                N'PWAIT_DIRECTLOGCONSUMER_GETNEXT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/PWAIT_DIRECTLOGCONSUMER_GETNEXT
                                N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/QDS_PERSIST_TASK_MAIN_LOOP_SLEEP
                                N'QDS_ASYNC_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/QDS_ASYNC_QUEUE
                                N'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP
                                N'QDS_SHUTDOWN_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/QDS_SHUTDOWN_QUEUE
                                N'REDO_THREAD_PENDING_WORK', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/REDO_THREAD_PENDING_WORK
                                N'REQUEST_FOR_DEADLOCK_SEARCH', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/REQUEST_FOR_DEADLOCK_SEARCH
                                N'RESOURCE_QUEUE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/RESOURCE_QUEUE
                                N'SERVER_IDLE_CHECK', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SERVER_IDLE_CHECK
                                N'SLEEP_BPOOL_FLUSH', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_BPOOL_FLUSH
                                N'SLEEP_DBSTARTUP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_DBSTARTUP
                                N'SLEEP_DCOMSTARTUP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_DCOMSTARTUP
                                N'SLEEP_MASTERDBREADY', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_MASTERDBREADY
                                N'SLEEP_MASTERMDREADY', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_MASTERMDREADY
                                N'SLEEP_MASTERUPGRADED', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_MASTERUPGRADED
                                N'SLEEP_MSDBSTARTUP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_MSDBSTARTUP
                                N'SLEEP_SYSTEMTASK', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_SYSTEMTASK
                                N'SLEEP_TASK', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_TASK
                                N'SLEEP_TEMPDBSTARTUP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SLEEP_TEMPDBSTARTUP
                                N'SNI_HTTP_ACCEPT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SNI_HTTP_ACCEPT
                                N'SP_SERVER_DIAGNOSTICS_SLEEP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SP_SERVER_DIAGNOSTICS_SLEEP
                                N'SQLTRACE_BUFFER_FLUSH', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SQLTRACE_BUFFER_FLUSH
                                N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SQLTRACE_INCREMENTAL_FLUSH_SLEEP
                                N'SQLTRACE_WAIT_ENTRIES', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/SQLTRACE_WAIT_ENTRIES
                                N'WAIT_FOR_RESULTS', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAIT_FOR_RESULTS
                                N'WAITFOR', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAITFOR
                                N'WAITFOR_TASKSHUTDOWN', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAITFOR_TASKSHUTDOWN
                                N'WAIT_XTP_RECOVERY', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAIT_XTP_RECOVERY
                                N'WAIT_XTP_HOST_WAIT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAIT_XTP_HOST_WAIT
                                N'WAIT_XTP_OFFLINE_CKPT_NEW_LOG', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAIT_XTP_OFFLINE_CKPT_NEW_LOG
                                N'WAIT_XTP_CKPT_CLOSE', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/WAIT_XTP_CKPT_CLOSE
                                N'XE_DISPATCHER_JOIN', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/XE_DISPATCHER_JOIN
                                N'XE_DISPATCHER_WAIT', -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/XE_DISPATCHER_WAIT
                                N'XE_TIMER_EVENT' -- HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/XE_TIMER_EVENT
                            )
         AND [WAITING_TASKS_COUNT] > 0 )
SELECT
    MAX([W1].[WAIT_TYPE]) AS [WAITTYPE],
    CAST(MAX([W1].[WAITS]) AS DECIMAL(16, 2)) AS [WAIT_S],
    CAST(MAX([W1].[RESOURCES]) AS DECIMAL(16, 2)) AS [RESOURCE_S],
    CAST(MAX([W1].[SIGNALS]) AS DECIMAL(16, 2)) AS [SIGNAL_S],
    MAX([W1].[WAITCOUNT]) AS [WAITCOUNT],
    CAST(MAX([W1].[PERCENTAGE]) AS DECIMAL(5, 2)) AS [PERCENTAGE],
    CAST(( MAX([W1].[WAITS]) / MAX([W1].[WAITCOUNT])) AS DECIMAL(16, 4)) AS [AVGWAIT_S],
    CAST(( MAX([W1].[RESOURCES]) / MAX([W1].[WAITCOUNT])) AS DECIMAL(16, 4)) AS [AVGRES_S],
    CAST(( MAX([W1].[SIGNALS]) / MAX([W1].[WAITCOUNT])) AS DECIMAL(16, 4)) AS [AVGSIG_S],
    CAST('HTTPS://WWW.SQLSKILLS.COM/HELP/WAITS/' + MAX([W1].[WAIT_TYPE]) AS XML) AS [HELP/INFO URL]
FROM
    [WAITS] AS [W1]
    INNER JOIN [WAITS] AS [W2] ON [W2].[ROWNUM] <= [W1].[ROWNUM]
GROUP BY
    [W1].[ROWNUM]
HAVING
    SUM([W2].[PERCENTAGE]) - MAX([W1].[PERCENTAGE]) < 95; -- PERCENTAGE THRESHOLD
GO

