SELECT
    [SJOB].[NAME] AS [JOBNAME] ,
    CASE [SJOB].[ENABLED]
      WHEN 1 THEN 'YES'
      WHEN 0 THEN 'NO'
    END AS [ISENABLED] ,
    [SJOB].[DATE_CREATED] AS [JOBCREATEDON] ,
    [SJOB].[DATE_MODIFIED] AS [JOBLASTMODIFIEDON] ,
    [SJSTP].[STEP_ID] AS [STEPNO] ,
    [SJSTP].[STEP_NAME] AS [STEPNAME] ,
    [SDBP].[NAME] AS [JOBOWNER] ,
    [SCAT].[NAME] AS [JOBCATEGORY] ,
    [SJOB].[DESCRIPTION] AS [JOBDESCRIPTION] ,
    CASE [SJSTP].[SUBSYSTEM]
      WHEN 'ACTIVESCRIPTING' THEN 'ACTIVEX SCRIPT'
      WHEN 'CMDEXEC' THEN 'OPERATING SYSTEM (CMDEXEC)'
      WHEN 'POWERSHELL' THEN 'POWERSHELL'
      WHEN 'DISTRIBUTION' THEN 'REPLICATION DISTRIBUTOR'
      WHEN 'MERGE' THEN 'REPLICATION MERGE'
      WHEN 'QUEUEREADER' THEN 'REPLICATION QUEUE READER'
      WHEN 'SNAPSHOT' THEN 'REPLICATION SNAPSHOT'
      WHEN 'LOGREADER' THEN 'REPLICATION TRANSACTION-LOG READER'
      WHEN 'ANALYSISCOMMAND' THEN 'SQL SERVER ANALYSIS SERVICES COMMAND'
      WHEN 'ANALYSISQUERY' THEN 'SQL SERVER ANALYSIS SERVICES QUERY'
      WHEN 'SSIS' THEN 'SQL SERVER INTEGRATION SERVICES PACKAGE'
      WHEN 'TSQL' THEN 'TRANSACT-SQL SCRIPT (T-SQL)'
      ELSE SJSTP.SUBSYSTEM
    END AS [STEPTYPE] ,
    [SPROX].[NAME] AS [RUNAS] ,
    [SJSTP].[DATABASE_NAME] AS [DATABASE] ,
    REPLACE(REPLACE(REPLACE([SJSTP].[COMMAND], CHAR(10) + CHAR(13), ' '), CHAR(13), ' '), CHAR(10), ' ') AS [EXECUTABLECOMMAND] ,
    CASE [SJSTP].[ON_SUCCESS_ACTION]
      WHEN 1 THEN 'QUIT THE JOB REPORTING SUCCESS'
      WHEN 2 THEN 'QUIT THE JOB REPORTING FAILURE'
      WHEN 3 THEN 'GO TO THE NEXT STEP'
      WHEN 4 THEN 'GO TO STEP: ' + QUOTENAME(CAST([SJSTP].[ON_SUCCESS_STEP_ID] AS VARCHAR(3))) + ' ' + [SOSSTP].[STEP_NAME]
    END AS [ONSUCCESSACTION] ,
    [SJSTP].[RETRY_ATTEMPTS] AS [RETRYATTEMPTS] ,
    [SJSTP].[RETRY_INTERVAL] AS [RETRYINTERVAL (MINUTES)] ,
    CASE [SJSTP].[ON_FAIL_ACTION]
      WHEN 1 THEN 'QUIT THE JOB REPORTING SUCCESS'
      WHEN 2 THEN 'QUIT THE JOB REPORTING FAILURE'
      WHEN 3 THEN 'GO TO THE NEXT STEP'
      WHEN 4 THEN 'GO TO STEP: ' + QUOTENAME(CAST([SJSTP].[ON_FAIL_STEP_ID] AS VARCHAR(3))) + ' ' + [SOFSTP].[STEP_NAME]
    END AS [ONFAILUREACTION],
    CASE
        WHEN [SSCH].[SCHEDULE_UID] IS NULL THEN 'NO'
        ELSE 'YES'
      END AS [ISSCHEDULED],
    [SSCH].[NAME] AS [JOBSCHEDULENAME],
    CASE 
        WHEN [SSCH].[FREQ_TYPE] = 64 THEN 'START AUTOMATICALLY WHEN SQL SERVER AGENT STARTS'
        WHEN [SSCH].[FREQ_TYPE] = 128 THEN 'START WHENEVER THE CPUS BECOME IDLE'
        WHEN [SSCH].[FREQ_TYPE] IN (4,8,16,32) THEN 'RECURRING'
        WHEN [SSCH].[FREQ_TYPE] = 1 THEN 'ONE TIME'
    END [SCHEDULETYPE], 
    CASE [SSCH].[FREQ_TYPE]
        WHEN 1 THEN 'ONE TIME'
        WHEN 4 THEN 'DAILY'
        WHEN 8 THEN 'WEEKLY'
        WHEN 16 THEN 'MONTHLY'
        WHEN 32 THEN 'MONTHLY - RELATIVE TO FREQUENCY INTERVAL'
        WHEN 64 THEN 'START AUTOMATICALLY WHEN SQL SERVER AGENT STARTS'
        WHEN 128 THEN 'START WHENEVER THE CPUS BECOME IDLE'
  END [OCCURRENCE], 
  CASE [SSCH].[FREQ_TYPE]
        WHEN 4 THEN 'OCCURS EVERY ' + CAST([FREQ_INTERVAL] AS VARCHAR(3)) + ' DAY(S)'
        WHEN 8 THEN 'OCCURS EVERY ' + CAST([FREQ_RECURRENCE_FACTOR] AS VARCHAR(3)) + ' WEEK(S) ON '
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 1 = 1 THEN 'SUNDAY' ELSE '' END
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 2 = 2 THEN ', MONDAY' ELSE '' END
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 4 = 4 THEN ', TUESDAY' ELSE '' END
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 8 = 8 THEN ', WEDNESDAY' ELSE '' END
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 16 = 16 THEN ', THURSDAY' ELSE '' END
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 32 = 32 THEN ', FRIDAY' ELSE '' END
                + CASE WHEN [SSCH].[FREQ_INTERVAL] & 64 = 64 THEN ', SATURDAY' ELSE '' END
        WHEN 16 THEN 'OCCURS ON DAY ' + CAST([FREQ_INTERVAL] AS VARCHAR(3)) + ' OF EVERY ' + CAST([SSCH].[FREQ_RECURRENCE_FACTOR] AS VARCHAR(3)) + ' MONTH(S)'
        WHEN 32 THEN 'OCCURS ON '
                 + CASE [SSCH].[FREQ_RELATIVE_INTERVAL]
                    WHEN 1 THEN 'FIRST'
                    WHEN 2 THEN 'SECOND'
                    WHEN 4 THEN 'THIRD'
                    WHEN 8 THEN 'FOURTH'
                    WHEN 16 THEN 'LAST'
                   END
                 + ' ' 
                 + CASE [SSCH].[FREQ_INTERVAL]
                    WHEN 1 THEN 'SUNDAY'
                    WHEN 2 THEN 'MONDAY'
                    WHEN 3 THEN 'TUESDAY'
                    WHEN 4 THEN 'WEDNESDAY'
                    WHEN 5 THEN 'THURSDAY'
                    WHEN 6 THEN 'FRIDAY'
                    WHEN 7 THEN 'SATURDAY'
                    WHEN 8 THEN 'DAY'
                    WHEN 9 THEN 'WEEKDAY'
                    WHEN 10 THEN 'WEEKEND DAY'
                   END
                 + ' OF EVERY ' + CAST([SSCH].[FREQ_RECURRENCE_FACTOR] AS VARCHAR(3)) + ' MONTH(S)'
    END AS [RECURRENCE], 
    CASE [SSCH].[FREQ_SUBDAY_TYPE]
        WHEN 1 THEN 'OCCURS ONCE AT ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_START_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')
        WHEN 2 THEN 'OCCURS EVERY ' + CAST([SSCH].[FREQ_SUBDAY_INTERVAL] AS VARCHAR(3)) + ' SECOND(S) BETWEEN ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_START_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')+ ' & ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_END_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')
        WHEN 4 THEN 'OCCURS EVERY ' + CAST([SSCH].[FREQ_SUBDAY_INTERVAL] AS VARCHAR(3)) + ' MINUTE(S) BETWEEN ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_START_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')+ ' & ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_END_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')
        WHEN 8 THEN 'OCCURS EVERY ' + CAST([SSCH].[FREQ_SUBDAY_INTERVAL] AS VARCHAR(3)) + ' HOUR(S) BETWEEN ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_START_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')+ ' & ' + STUFF(STUFF(RIGHT('000000' + CAST([SSCH].[ACTIVE_END_TIME] AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':')
    END [FREQUENCY], 
    STUFF(STUFF(CAST([SSCH].[ACTIVE_START_DATE] AS VARCHAR(8)), 5, 0, '-'), 8, 0, '-') AS [SCHEDULEUSAGESTARTDATE], 
    STUFF(STUFF(CAST([SSCH].[ACTIVE_END_DATE] AS VARCHAR(8)), 5, 0, '-'), 8, 0, '-') AS [SCHEDULEUSAGEENDDATE], 
    [SSCH].[DATE_CREATED] AS [SCHEDULECREATEDON], 
    [SSCH].[DATE_MODIFIED] AS [SCHEDULELASTMODIFIEDON],
    CASE [SJOB].[DELETE_LEVEL]
        WHEN 0 THEN 'NEVER'
        WHEN 1 THEN 'ON SUCCESS'
        WHEN 2 THEN 'ON FAILURE'
        WHEN 3 THEN 'ON COMPLETION'
    END AS [JOBDELETIONCRITERION]
FROM
    [MSDB].[DBO].[SYSJOBSTEPS] AS [SJSTP]
    INNER JOIN [MSDB].[DBO].[SYSJOBS] AS [SJOB] ON [SJSTP].[JOB_ID] = [SJOB].[JOB_ID]
    LEFT JOIN [MSDB].[DBO].[SYSJOBSTEPS] AS [SOSSTP] ON [SJSTP].[JOB_ID] = [SOSSTP].[JOB_ID] AND [SJSTP].[ON_SUCCESS_STEP_ID] = [SOSSTP].[STEP_ID]
    LEFT JOIN [MSDB].[DBO].[SYSJOBSTEPS] AS [SOFSTP] ON [SJSTP].[JOB_ID] = [SOFSTP].[JOB_ID] AND [SJSTP].[ON_FAIL_STEP_ID] = [SOFSTP].[STEP_ID]
    LEFT JOIN [MSDB].[DBO].[SYSPROXIES] AS [SPROX] ON [SJSTP].[PROXY_ID] = [SPROX].[PROXY_ID]
    LEFT JOIN [MSDB].[DBO].[SYSCATEGORIES] AS [SCAT] ON [SJOB].[CATEGORY_ID] = [SCAT].[CATEGORY_ID]
    LEFT JOIN [MSDB].[SYS].[DATABASE_PRINCIPALS] AS [SDBP] ON [SJOB].[OWNER_SID] = [SDBP].[SID]
    LEFT JOIN [MSDB].[DBO].[SYSJOBSCHEDULES] AS [SJOBSCH] ON [SJOB].[JOB_ID] = [SJOBSCH].[JOB_ID]
    LEFT JOIN [MSDB].[DBO].[SYSSCHEDULES] AS [SSCH] ON [SJOBSCH].[SCHEDULE_ID] = [SSCH].[SCHEDULE_ID]
ORDER BY
    [JOBNAME] ,
    [STEPNO]

